---
  # these two file pointers must be fully qualified paths including the filename.
  wsjtLog: /Users/asadolahseghatoleslami/Documents/hamradio/DVRA/EME Project/testData/wsjtx.log
  map65Log: /Users/asadolahseghatoleslami/Documents/hamradio/DVRA/EME Project/testData/map65.log
  testLog: /Users/asadolahseghatoleslami/Documents/hamradio/DVRA/EME Project/testData/wsjtx_test.log
  # times must be in RFC3339 format like this: 2022-04-06T03:15:15Z
  startTime: 2022-04-05T19:08:00Z
  endTime: 2022-10-31T01:48:30Z
